<?php
/**
 * Modular Seed Architecture - Core Pages Worker
 *
 * Creates prototype structural pages (Home, Blog, About, Contact) idempotently.
 *
 * @package {{PLUGIN_SLUG}}
 */

defined('ABSPATH') || exit;

class {{UPPER_PLUGIN_SLUG}}_Seed_Pages {

    public static function seed() {
        $created_pages = [];

        $default_pages = [
            'home' => [
                'title'   => 'Home',
                'content' => '<!-- wp:pattern {"slug":"{{THEME_SLUG}}/hero-banner"} /-->',
                'status'  => 'publish',
            ],
            'blog' => [
                'title'   => 'Blog',
                'content' => '',
                'status'  => 'publish',
            ],
            'about' => [
                'title'   => 'About Us',
                'content' => '<p>Welcome to our company. This page was generated by {{THEME_NAME}} seed pipeline.</p>',
                'status'  => 'publish',
            ],
            'contact' => [
                'title'   => 'Contact',
                'content' => '<p>Get in touch with us using the form below.</p><!-- wp:shortcode -->[{{THEME_SLUG}}_contact_form]<!-- /wp:shortcode -->',
                'status'  => 'publish',
            ],
        ];

        foreach ($default_pages as $slug => $data) {
            $existing_page = get_page_by_path($slug);
            if (!$existing_page) {
                $page_id = wp_insert_post([
                    'post_title'     => $data['title'],
                    'post_name'      => $slug,
                    'post_content'   => $data['content'],
                    'post_status'    => $data['status'],
                    'post_type'      => 'page',
                    'comment_status' => 'closed',
                ]);

                if (!is_wp_error($page_id)) {
                    $created_pages[$slug] = $page_id;
                }
            } else {
                $created_pages[$slug] = $existing_page->ID;
            }
        }

        // Configure Static Front Page settings if Home and Blog exist
        if (!empty($created_pages['home']) && !empty($created_pages['blog'])) {
            $current_front = get_option('page_on_front');
            if (empty($current_front)) {
                update_option('show_on_front', 'page');
                update_option('page_on_front', $created_pages['home']);
                update_option('page_for_posts', $created_pages['blog']);
            }
        }

        return [
            'status' => 'complete',
            'pages'  => $created_pages,
        ];
    }
}
